### ISSUE TITLE
initialDelaySeconds in livenessProb time configuration is too short

### ISSUE THREAD

**Issue by rootsongjc** [redhat-developer-demos/istio-tutorial#71]
The `initialDelaySeconds` time config in Deployment.yml is too short.
Customer and preference service stand up too slow which need more than **10** seconds, the pods will restart automatically. After I change it to 20 seconds, that works.
```yaml
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 1
```
